# Generated by Django 5.1.2 on 2025-04-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('career_type', models.CharField(choices=[('film', 'Film'), ('drama', 'Drama'), ('variety', 'Variety Show'), ('music', 'Music'), ('victory', 'Victory/Award'), ('other', 'Other')], max_length=20)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_special', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='career/')),
            ],
            options={
                'verbose_name_plural': 'Career Entries',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
